package com.sfl.coolmonkey.coolfs.api.model.common;

/**
 * User: Arthur Asatryan
 * Company: SFL LLC
 * Date: 10/11/15
 * Time: 10:33 PM
 */
public enum CommonErrorType {
    //region Company

    //region Address lock
    ADDRESS_ALREADY_LOCKED,
    ADDRESS_LOCK_NOT_FOUND_FOR_OPERATOR,
    ADDRESS_LOCK_NOT_FOUND_FOR_ADDRESS,
    NO_ADDRESS_TO_LOCK_FOR_OPERATOR,
    ADDRESS_CAN_NOT_BE_LOCKED,
    ADDRESS_DISABLED_CAN_NOT_BE_LOCKED,
    ADDRESS_INACTIVE,
    //endregion

    //region Operator
    EXISTING_EMAIL,
    OPERATOR_NO_HAVE_CURRENT_SUBSCRIPTION_FOR_LOCK,
    OPERATOR_NO_HAVE_CURRENT_SUBSCRIPTION_FOR_ADD_DISPOSITION,
    //endregion

    //region Phone type
    PHONE_TYPE_EXISTING_NAME,
    //endregion

    //region User
    USER_WITH_PROVIDED_EMAIL_ALREADY_EXISTS,
    USER_INVALID_VERIFICATION_TOKEN,
    USER_NOT_VERIFIED,
    USER_FORGOT_PASSWORD_TOKEN_NOT_FOUND,
    USER_NOT_ACTIVATED,
    USER_HAS_ADDRESSES_ASSIGNED,
    USER_HAS_LOCKED_ADDRESSES,
    //endregion

    //region Company manager
    COMPANY_MANAGER_MISSING_EMAIL,
    COMPANY_MANAGER_MISSING_PASSWORD,
    COMPANY_MANAGER_INVALID_EMAIL_FORMAT,
    COMPANY_MANAGER_INVALID_PASSWORD_FORMAT,
    //endregion

    //region Authentication
    AUTHENTICATION_MISSING_EMAIL,
    AUTHENTICATION_MISSING_PASSWORD,
    AUTHENTICATION_INVALID_EMAIL_FORMAT,
    AUTHENTICATION_INVALID_PASSWORD_FORMAT,
    AUTHENTICATION_INVALID_CREDENTIALS,
    EXTERNAL_AUTHENTICATION_NOT_FOUND,
    EXTERNAL_AUTHENTICATION_ALLREADY_EXISTS,
    //endregion

    //region Subscriptions

    NOT_ENOUGH_CREDITS,

    //region Call attempt
    AMOUNT_IS_NOT_DIVISIBLE_BY_CALL_ATTEMPT_SUBSCRIPTION_PRICE,
    ALREADY_HAS_PER_CALL_ATTEMPT_SUBSCRIPTION_WITH_AUTO_RECHARGE,
    CALL_ATTEMPT_SUBSCRIPTION_IS_NOT_LAST_CREATED,
    //endregion

    //region Periodical
    ALREADY_HAS_TWO_NON_CURRENT_PERIODICAL_SUBSCRIPTIONS_IN_THE_FUTURE,
    PERIODICAL_SUBSCRIPTIONS_EXIST_AFTER_DATE_WHEN_NEW_IS_AUTORECHARGE,
    PERIODICAL_SUBSCRIPTION_OVERLAPS_WITH_EXISTING,
    ALREADY_HAS_PERIODICAL_SUBSCRIPTION_WITH_AUTO_RECHARGE,
    CANNOT_CANCEL_CURRENT_PERIODICAL_SUBSCRIPTION,
    //endregion

    //endregion

    //region Invitation
    ALTERNATIVE_EMAIL_EXISTS,
    ALTERNATIVE_EMAIL_DOES_NOT_EXIST,
    //endregion

    //endregion

    //region Address
    CAMPAIGN_INVALID_OPERATORS,
    MISSING_COMPANY_UUID,
    SCRIPT_EXISTING_NAME,
    DC_DEFINITION_EXISTING_NAME,

    //region Field Definition
    FIELD_DEFINITION_EXISTING_FIELD_ID,
    FIELD_DEFINITION_EXISTING_FIELD_NAME,
    FIELD_DEFINITION_COUNT_EXCEEDED_UNPAID,
    FIELD_DEFINITION_COUNT_EXCEEDED_PAID,
    FIELD_OPTION_DEFINITION_USED_ON_ADDRESSES,
    FIELD_USED_ON_SCRIPTS_DEACTIVATE,
    FIELD_USED_ON_SCRIPTS_DELETE,
    FIELD_IS_ONLY_ON_SCRIPT,
    //endregion

    CAMPAIGN_EXISTING_NAME,
    EMAIL_TEMPLATE_EXISTING_NAME,
    ADDRESS_LOCKED,
    ADDRESS_LAST_DC_DOES_NOT_HAVE_FOLLOW_UP_START_DATE,
    ADDRESS_LAST_DC_DOES_NOT_HAVE_FOLLOW_UP_END_DATE,

    ADDRESS_ALREADY_EXISTS_FOR_DOSSIER_AND_ESTABLISHMENT_NUMBERS,
    //endregion

    //region Campaign
    CAMPAIGN_NOT_FOUND_FOR_CAMPAIGN_AND_OPERATOR,
    CAMPAIGN_USED_IN_ADDRESSES,
    CAMPAIGN_USED_IN_IMPORT,
    //endregion

    //region Import
    IMPORT_FILE_EMPTY,
    IMPORT_FILE_MAX_SIZE_EXCEEDED,
    IMPORT_FILE_INVALID_EXTENSION,
    IMPORT_FILE_ALREADY_UPLOADED,

    IMPORT_MISSING_MANDATORY_FIELDS,
    IMPORT_INVALID_FIELD_FORMAT,
    IMPORT_EMPTY_HEADER_VALUE,
    IMPORT_DUPLICATE_HEADER_VALUES,
    IMPORT_PARSING_ERROR,
    //endregion

    //region Address filter
    FIELD_OPTION_DEFINITION_USED_ON_ADDRESS_FILTERS,
    //endregion

    //region Disposition
    DELETE_DISPOSITION_USED_IN_ADDRESSES,
    DELETE_DISPOSITION_USED_IN_SCRIPTS,
    DEACTIVATE_DISPOSITION_USED_IN_ADDRESSES,
    DEACTIVATE_DISPOSITION_USED_IN_SCRIPTS,
    //endregion

    //region EmailTemplate
    EMAIL_TEMPLATE_USED_ON_DISPOSITIONS_DELETE,
    EMAIL_TEMPLATE_USED_ON_DISPOSITIONS_DEACTIVATE,
    //endregion

    //region Cronofy
    OPERATOR_NOT_ABLE_TO_ACCESS_CRONOFY_API,
    OPERATOR_NOT_ABLE_TO_READ_EVENTS,
    //endregion

    //region UserAccessToken
    INVALID_ACCESS_TOKEN,
    //endregion

    //region Script
    INVALID_SCRIPT_UUID,
    //endregion

    //region UserColumnSettings
    CAN_NOT_FIND_USER_COLUMN_SETTINGS,
    //endregion

    //region Telephony
    TELEPHONY_USERNAME_ALREADY_EXISTS,
    //endregion

    //region Common
    RECORD_NOT_EXIST,
    //endregion

    //region Job States
    NOT_ENDED_JOB_EXISTS
    //endregion
}
