package com.sfl.coolmonkey.coolfs.api.model.storage;

/**
 * User: Arthur Asatryan
 * Company: SFL LLC
 * Date: 4/1/16
 * Time: 2:25 PM
 */
public enum FileOriginModel {
    CLIENT_LOGO,
    CONTENT_PARTNER_LOGO,
    CONTENT_PARTNER_CATEGORY_ICON,
    CONTENT_PARTNER_LOCATION_LOGO,
    CONTENT_PARTNER_LOCATION_IMAGES,
    CONTENT_PARTNER_LOCATION_BANNER,
    CAMPAIGN_VISUALS_LOGO,
    CAMPAIGN_VISUALS_BANNER,
    VOUCHER_GENERATION_REQUEST,
    BACK_OFFICE_USER_AVATAR,
    BARCODE_IMPORT_FILE_ORIGINAL,
    BARCODE_IMPORT_FILE_GENERATED,
    BARCODE_INVALID_IMPORT_FILE,
    CAMPAIGN_CONTENT_PARTNER_MAIN_IMAGE,
    CAMPAIGN_CONTENT_PARTNER_BANNER
}
